#!/bin/sh

# Fix for nvm:
# This ensures that the nvm command is available to the script.
# It sources the nvm script if it exists in the default location.
if [ -f ~/.nvm/nvm.sh ]; then
  . ~/.nvm/nvm.sh
fi

npx --no -- commitlint --edit "$1" --config configs/linting/commitlint.config.cjs