name: ESLint Quality Reporting

on:
  push:
    branches:
      - main
      - nightly
  pull_request:
    branches:
      - main
      - nightly

jobs:
  eslint-report:
    name: ESLint Quality Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint and generate report
        run: npm run lint:report

      - name: Upload ESLint report artifact
        uses: actions/upload-artifact@v4
        with:
          name: eslint-report
          path: eslint_report.json

      - name: Analyze ESLint report for regressions
        id: eslint_check
        run: node scripts/ci/check-eslint-regressions.js

      - name: Create GitHub issue for ESLint regression
        if: steps.eslint_check.outputs.regression_detected == 'true'
        uses: actions/create-issue@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Code Quality Regression Detected"
          body: |
            A regression in code quality has been detected.
            Please review the attached ESLint report for details.
          labels: bug, technical-debt

      # Placeholder for Google Sheets Integration
      - name: Update Google Sheets
        if: always()
        run: echo "TODO: Add Google Sheets integration using secrets."

      # Placeholder for Discord Notification
      - name: Send Discord Notification
        if: always()
        run: echo "TODO: Add Discord notification using secrets."
