name: Nightly Branch CI

on:
  push:
    branches: [nightly]
  pull_request:
    branches: [nightly]

env:
  NODE_VERSION: '22'

jobs:
  lint-and-format:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Check formatting
        run: npm run format:check

      - name: Check dependencies
        run: npm run deps:audit

  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: lint-and-format
    strategy:
      matrix:
        build-mode: [nightly, production]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build (${{ matrix.build-mode }})
        run: npm run build:${{ matrix.build-mode }}

      - name: Run health check
        run: |
          npm run preview &
          sleep 5
          npm run health-check http://localhost:4173
          pkill -f "vite preview" || true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.build-mode }}
          path: dist/
          retention-days: 7

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit --audit-level moderate

      - name: Check for vulnerabilities
        run: |
          if npm audit --audit-level high --json | jq '.vulnerabilities | length' | grep -v '^0$'; then
            echo "High severity vulnerabilities found!"
            exit 1
          fi