name: Create GitHub Release (Major/Minor Only)

on:
  push:
    tags:
      # Match tags like v1.0.0, v2.1.0 — but NOT v1.0.1, v2.3.4
      - 'v[0-9]+.[0-9]+.0'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify branch is main
        run: |
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "Detected branch: $BRANCH"
          if [ "$BRANCH" != "main" ]; then
            echo "::error::Releases can only be created from the 'main' branch"
            exit 1
          fi

      - name: Generate GitHub Release from Tag
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}