name: Create GitHub Release (Major/Minor Only)

on:
  push:
    tags:
      # Match tags like v1.0.0, v2.1.0 — but NOT v1.0.1, v2.3.4
      - 'v[0-9]+.[0-9]+.0'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate GitHub Release from Tag
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}